FROM node:14-alpine as build-stage
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY babel.config.js vue.config.js ./
COPY src ./src
COPY public ./public
RUN npm run build

FROM uhziel/yireader-api:edge as production-stage
COPY --from=build-stage /app/dist ./dist